# Generated by Django 3.2.7 on 2021-09-03 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0005_rename_cat_photo_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('5', '5:00AM-6:45AM'), ('7', '7:00AM-8:45AM'), ('9', '9:00AM-10:45AM'), ('11', '11:00AM-12:45AM'), ('13', '13:00AM-14:45AM'), ('15', '15:00AM-16:45AM'), ('17', '17:00AM-18:45AM'), ('19', '19:00AM-20:45AM'), ('21', '21:00AM-22:45AM')], default='5', max_length=2)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
